/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.javaconverter;


/**
 *
 * @author Flyedest
 */
public class JavaConverterUI extends javax.swing.JFrame {

    /**
     * Creates new form JavaConverterUI
     */
    public JavaConverterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        dDec = new javax.swing.JRadioButton();
        dBin = new javax.swing.JRadioButton();
        dHex = new javax.swing.JRadioButton();
        dOcta = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        pDec = new javax.swing.JRadioButton();
        pOcta = new javax.swing.JRadioButton();
        pHex = new javax.swing.JRadioButton();
        pBin = new javax.swing.JRadioButton();
        dCustomField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dCustom = new javax.swing.JRadioButton();
        pCustomField = new javax.swing.JTextField();
        pCustom = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text1.setText("110,101");
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        text2.setOpaque(false);
        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(dDec);
        dDec.setText("DEC");
        dDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDecActionPerformed(evt);
            }
        });

        buttonGroup1.add(dBin);
        dBin.setText("BIN");

        buttonGroup1.add(dHex);
        dHex.setText("HEX");

        buttonGroup1.add(dOcta);
        dOcta.setText("OCTA");
        dOcta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dOctaActionPerformed(evt);
            }
        });

        jLabel1.setText("De:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("Para:");

        buttonGroup2.add(pDec);
        pDec.setSelected(true);
        pDec.setText("DEC");
        pDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDecActionPerformed(evt);
            }
        });

        buttonGroup2.add(pOcta);
        pOcta.setText("OCTA");

        buttonGroup2.add(pHex);
        pHex.setText("HEX");

        buttonGroup2.add(pBin);
        pBin.setText("BIN");

        jButton1.setText("Converter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        buttonGroup1.add(dCustom);
        dCustom.setSelected(true);

        buttonGroup2.add(pCustom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(dDec)
                                    .addComponent(dOcta)
                                    .addComponent(dBin)
                                    .addComponent(dHex))
                                .addGap(32, 32, 32)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dCustom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dCustomField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(pDec)
                            .addComponent(pOcta)
                            .addComponent(pHex)
                            .addComponent(pBin)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pCustom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pCustomField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(dDec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dBin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dHex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dOcta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dCustom)
                            .addComponent(dCustomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pOcta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pHex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pBin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pCustom)
                            .addComponent(pCustomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void dDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dDecActionPerformed

    private void pDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pDecActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        text2.setText(getData());

    }//GEN-LAST:event_text1ActionPerformed

    private void dOctaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dOctaActionPerformed
        text2.setText(getData());
    }//GEN-LAST:event_dOctaActionPerformed
    
    public String getData(){
        String number, result;
        int base, destiny = 0;
        number = text1.getText();
        if(pBin.isSelected()){
            destiny = 2;
        }else if(pHex.isSelected()){
            destiny = 16;
        }else if(pOcta.isSelected()){
            destiny = 8;
        }else if(pDec.isSelected()){
            destiny = 10;
        }else if(pCustom.isSelected()){
            String custom = pCustomField.getText();
            destiny = (int)custom.charAt(0) - 55;
            
        }
        
        if(dBin.isSelected()){
            base = 2;
            result = div(base, number, destiny);
            return result;
            
        }else if(dHex.isSelected()){
            base = 16;
            result = div(base, number, destiny);
            return result;
            
        }else if(dOcta.isSelected()){
            base = 8;
            result = div(base, number, destiny);
            return result;
            
        }else if(dDec.isSelected()){
            base = 10;
            result = div(base, number, destiny);
            return result;
            
        }else if(dCustom.isSelected()){
            String custom = dCustomField.getText();
            base = (int)custom.charAt(0) - 55;
            System.out.println(base);
            result = div(base, number, destiny);
            return result;
            
        }
        return "";
    }
    
    public static String poli(int base, String number){
        String[] arr = new String[2];
        String neg = "";
        boolean flag = false;
        int ch, n = 0;
        if(number.contains("-")){
            neg = "-";
            number = number.substring(1);
        }
        if(number.contains(",")){
            arr = number.split(",");
            flag = true;
        }else{
            arr[0] = number;
            arr[1] = "0";
        }
        
        int t = arr[0].length()-1,
                result = 0;
        float subresult = 0;
        
        for(int i = 0;i <= arr[0].length()-1;i++,t--){
            if(Character.isDigit(arr[0].charAt(i)) == false){
                n = Character.getNumericValue(arr[0].charAt(i));
                result += n * Math.pow(base,t);
                System.out.println(n + "\n" +result);
            }else{
                n = Integer.parseInt(Character.toString(arr[0].charAt(i)));
                result += n * Math.pow(base,t);
                System.out.println(n + "\n" +result);
            }         
        }
        if(flag){
            t = -1;
            for(int i = 0; i <= arr[1].length()-1;i++,t--){
                if(Character.isDigit(arr[1].charAt(i)) == false){
                    n = Character.getNumericValue(arr[1].charAt(i));
                    subresult += n * Math.pow(base,t);
                }else{
                    n = Integer.parseInt(Character.toString(arr[1].charAt(i)));
                    subresult += n * Math.pow(base,t);
                }
            }
            return (neg + Float.toString(result + subresult));
        }else{
            return (neg + Integer.toString(result));
        }
        
        
    }
    
    public static String div(int base, String number, int destiny){
        
        String preresult = poli(base, number);
        String[] arr = new String[2];
        String neg = "";
        boolean flag = false;
        int ch, n = 0;
        if(preresult.contains("-")){
            neg = "-";
            preresult = preresult.substring(1);
        }
        if(preresult.contains(".")){
            arr = preresult.split(".");
            flag = true;
        }else{
            arr[0] = number;
            
        }
        String result = "";
        int num = Integer.parseInt(arr[0]);
        while(num >= destiny){
            int mod = num % destiny;
            if(mod > 9){
                result += (char)mod + 55;
            }else{
                result += mod;
            }
            num = (int) num / destiny;
        }
        return neg + reverse(result);
    }
    
    public static String reverse(String text){
        int len = text.length();
        char[] tempCharArray = new char[len];
        char[] charArray = new char[len];
        
        for (int i = 0; i < len; i++) {
            tempCharArray[i] = text.charAt(i);
        }
        for (int j = 0; j < len; j++) {
            charArray[j] = tempCharArray[len - 1 - j];
        }
 
        String reverse = new String(charArray);
        
        return reverse;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaConverterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton dBin;
    private javax.swing.JRadioButton dCustom;
    private javax.swing.JTextField dCustomField;
    private javax.swing.JRadioButton dDec;
    private javax.swing.JRadioButton dHex;
    private javax.swing.JRadioButton dOcta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton pBin;
    private javax.swing.JRadioButton pCustom;
    private javax.swing.JTextField pCustomField;
    private javax.swing.JRadioButton pDec;
    private javax.swing.JRadioButton pHex;
    private javax.swing.JRadioButton pOcta;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables
}
